title: Processing Config
description: Schema for data processing configuration
type: object
properties:
  processingConfig:
    type: object
    properties:
      cellSizeDistribution:
        $ref: ./processing-config-bodies/ProcessingConfigCellSizeDistribution.v1.yaml
      mitochondrialContent:
        $ref: ./processing-config-bodies/ProcessingConfigMitochondrialContent.v1.yaml
      readAlignment:
        $ref: ./processing-config-bodies/ProcessingConfigReadAlignment.v1.yaml
      classifier:
        $ref: ./processing-config-bodies/ProcessingConfigClassifier.v1.yaml
      numGenesVsNumUmis:
        $ref: ./processing-config-bodies/ProcessingConfigNumGenesVsNumUMIs.v1.yaml
      doubletScores:
        $ref: ./processing-config-bodies/ProcessingConfigDoubletScores.v1.yaml
      dataIntegration:
        $ref: ./processing-config-bodies/ProcessingConfigDataIntegration.v1.yaml
      configureEmbedding:
        $ref: ./processing-config-bodies/ProcessingConfigConfigureEmbedding.v1.yaml
      meta:
        $ref: ./processing-config-bodies/ProcessingConfigMeta.v1.yaml
