title: Data Integration
type: object
description: Processing config body for Data Integration filter.
properties:
  dataIntegration:
    type: object
    properties:
      method:
        type: string
        enum:
          - seuratv4
          - seuratv3
          - harmony
          - conos
          - liger
          - fastmnn
          - unisample
      methodSettings:
        type: object
        properties:
          seuratv4:
            type: object
            properties:
              numGenes:
                type: number
              normalisation:
                type: string
                enum:
                  - logNormalize
                  - scTransform
            required:
              - numGenes
              - normalisation
    required:
      - method
      - methodSettings
  dimensionalityReduction:
    type: object
    properties:
      method:
        type: string
        enum:
          - rpca
          - cca
      numPCs:
        type: number
        minimum: 1
      excludeGeneCategories:
        type: array
        items:
          type: string
          enum:
            - ribosomal
            - mitochondrial
            - cellCycle
    required:
      - method
      - numPCs
      - excludeGeneCategories
required:
  - dataIntegration
  - dimensionalityReduction