title: Cell Size Distribution
type: object
additionalProperties:
  type: object
  properties:
    filterSettings:
      type: object
      properties:
        minCellSize:
          type: number
        binStep:
          type: number
description: Processing config body for Cell Size Distribution filter.
properties:
  enabled:
    type: boolean
  auto:
    type: boolean
  filterSettings:
    type: object
    properties:
      minCellSize:
        type: number
      binStep:
        type: number
required:
  - filterSettings
