title: Classifier
type: object
description: Processing config body for Classifier filter.
properties:
  enabled:
    type: boolean
  auto:
    type: boolean
  filterSettings:
    type: object
    properties:
      FDR:
        type: number
required:
  - filterSettings
