{{- if .Values.service.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sandboxId: "{{ .Values.biomageCi.sandboxId }}"

  annotations:
    kubernetes.io/ingress.class: alb
{{- if .Values.ingress.tls.enabled }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port":
      "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/certificate-arn: >-
      {{ .Values.myAccount.acmCertificate }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
{{- end }}
{{- if eq .Values.myAccount.publicFacing "true" }}
    alb.ingress.kubernetes.io/scheme: internet-facing
{{- else }}
    alb.ingress.kubernetes.io/scheme: internal
{{- end }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.loadBalancerHealthCheck.successCodes }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "{{ .Values.loadBalancerHealthCheck.periodSeconds }}"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "{{ .Values.loadBalancerHealthCheck.timeoutSeconds }}"
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.loadBalancerHealthCheck.path }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.loadBalancerHealthCheck.scheme }}
    alb.ingress.kubernetes.io/healthy-threshold-count: "{{ .Values.loadBalancerHealthCheck.successThreshold }}"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "{{ .Values.loadBalancerHealthCheck.failureThreshold }}"
    alb.ingress.kubernetes.io/group.name: {{ .Values.kubernetes.env }}
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - host: {{ template "hostname" . }}
    http:
      &httpRule
      paths:
{{- if .Values.ingress.tls.enabled }}
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
{{- end }}
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ template "appname" . }}
            port:
              number: {{ .Values.service.externalPort }}
{{- if .Values.service.additionalHosts }}
  - host: {{ .Values.myAccount.domainName }}
    http:
      <<: *httpRule
{{- end -}}
{{- end -}}
