apiVersion: v1
myAccount:
  domainName: FILLED_IN_BY_CI
  region: FILLED_IN_BY_CI
  accountId: FILLED_IN_BY_CI
  publicFacing: FILLED_IN_BY_CI
  acmCertificate: FILLED_IN_BY_CI
  selfSignedCertificate: FILLED_IN_BY_CI
  datadogEnabled: FILLED_IN_BY_CI
  datadogApiKey: FILLED_IN_BY_CI
  datadogAppKey: FILLED_IN_BY_CI
  workerTimeout: FILLED_IN_BY_CI
  workerScaleToZero: FILLED_IN_BY_CI
  #FILLED IN BY IAC CI
