name: Create backup of dynamodb tables
on: 
  workflow_dispatch:
    inputs:
      tables:
        description: 'Space separated ids of tables to backup, all if not specified'
        required: false
        default: 'all'

jobs:
  backup-tables: 
    name: Create backup of dynamodb tables
    runs-on: ubuntu-20.04
    env:
      TABLES: ${{ github.event.inputs.tables }}
    steps:
      - id: set-up-creds
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - id: backup-tables
        name: Create backup of dynamodb tables
        run: |-
          if [[ "$TABLES" == "all" ]]; then
            tables_to_backup=($(aws dynamodb list-tables | jq -r '.TableNames | .[]' | tr '\r\n' ' '))
          else
            tables_to_backup=(`echo ${TABLES}`)
          fi

          current_date=$(date '+%Y-%m-%d.%H-%M-%S')
          for table in $tables_to_backup; do
            backup_name="${table}-backup-${current_date}"
            echo "Creating backup with name $backup_name for table $table"
            message=$(aws dynamodb create-backup --table-name $table --backup-name "${table}-backup-${current_date}")
            echo $message
          done
