targetSystem: "linux"
datadog:
  logs:
    enabled: false
  processAgent:
    enabled: true
    processCollection: true
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: false
    collectDNSStats: false
  containerExclude:  "name:.*"
  containerIncludeMetrics:  "name:biomage-node-chart"
clusterAgent:
  enabled: true
  replicas: 2
agents:
  enabled: true